[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.format]
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.lint]
command = "cargo"
args = ["clippy", "--fix"]

[tasks.build]
command = "cargo"
args = ["build"]
