[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.format]
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.lint]
command = "cargo"
args = ["clippy", "--fix", "--allow-dirty"]

[tasks.build-only]
command = "cargo"
args = ["build"]

[tasks.build]
dependencies = [
    "lint", "build-only", "format",
]

[tasks.test]
dependencies = [
    "build-only"
]
command = "cargo"
args = ["test"]

[task.build-prod]
