[tasks.clean]
dependencies = ["server-clean", "client-clean"]

[tasks.build]
dependencies = ["server-build", "client-build"]

[tasks.format]
dependencies = ["server-format", "client-format"]

#server
[tasks.server-clean]
command = "cargo"
args = ["clean"]

[tasks.server-format]
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.server-lint]
command = "cargo"
args = ["clippy", "--fix", "--allow-dirty"]

[tasks.server-build]
command = "cargo"
args = ["build"]

[tasks.server-build-prod]
command = "cargo"
args = ["build", "--release"]

[tasks.server-test]
dependencies = [
    "server-build"
]
command = "cargo"
args = ["test"]

[tasks.run]
dependencies = [
    "server-build"
]
command = "cargo"
args = ["run"]

#client
[tasks.client-clean]
cwd = "./src/vue-client"
script = [
    "npm run clean"
]

[tasks.client-format]
cwd = "./src/vue-client"
condition =  { files_modified = {input = ["./**/*"], output = ["../../public/*"]}}
script = [
    "npm run format"
]

[tasks.client-build]
cwd = "./src/vue-client"
condition =  { files_modified = {input = ["./**/*"], output = ["../../public/*"]}}
script = [
    "npm run dev"
]
