[tasks.server-clean]
command = "cargo"
args = ["clean"]

[tasks.server-format]
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.server-lint]
command = "cargo"
args = ["clippy", "--fix", "--allow-dirty"]

[tasks.server-build-only]
command = "cargo"
args = ["build"]

[tasks.server-build-only-prod]
command = "cargo"
args = ["build", "--release"]

[tasks.server-build]
dependencies = [
    "server-lint", "server-build-only", "server-format",
]

[tasks.server-build-prod]
dependencies = [
    "server-lint", "server-build-only-prod", "server-format",
]

[tasks.server-test]
dependencies = [
    "server-build-only"
]
command = "cargo"
args = ["test"]

[tasks.server-run]
dependencies = [
    "server-build"
]
command = "cargo"
args = ["run"]

[tasks.client-clean]
