[tasks.clean]
dependencies = ["server-clean", "client-clean"]

[tasks.build-only]
dependencies = ["server-build-only", "client-build-only"]

#server
[tasks.server-clean]
command = "cargo"
args = ["clean"]

[tasks.server-format]
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.server-lint]
command = "cargo"
args = ["clippy", "--fix", "--allow-dirty"]

[tasks.server-build-only]
command = "cargo"
args = ["build"]

[tasks.server-build-only-prod]
command = "cargo"
args = ["build", "--release"]

[tasks.server-build]
dependencies = [
    "server-lint", "server-build-only", "server-format",
]

[tasks.server-build-prod]
dependencies = [
    "server-lint", "server-build-only-prod", "server-format",
]

[tasks.server-test]
dependencies = [
    "server-build-only"
]
command = "cargo"
args = ["test"]

[tasks.run]
dependencies = [
    "server-build"
]
command = "cargo"
args = ["run"]

#client
[tasks.client-clean]
cwd = "./src/vue-client"
script = [
    "npm run clean"
]

[tasks.client-format]
cwd = "./src/vue-client"
script = [
    "npm run format"
]

[tasks.client-build-only]
cwd = "./src/vue-client"
condition =  { files_modified = {input = ["./**/*"], output = ["../../public/*"]}}
script = [
    "npm run dev"
]
