name: Install and test all
on:
  push:
    branches: [ $default-branch,  adding_gh_actions ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ $default-branch ]
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.9.0
        with:
          version: 16
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo install --force cargo-make
      - name: Install App
        run: cargo make install
      - name: Test App
        run: cargo make test
