name: Install and test all
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ $default-branch ]
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node and npm
        run: sudo apt-get install nodejs npm
      - name: Install LLVM and Clang
        run: sudo apt-get install llvm
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Install cargo-make
        run: cargo install --force cargo-make
      - name: Install App
        run: cargo make install
      - name: Test App
        run: cargo make test
